/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsSystemIdRouteImport } from './routes/systems.$systemId'
import { Route as OperatorSessionIdRouteImport } from './routes/operator_.$sessionId'
import { Route as SystemsSystemIdServicesRouteImport } from './routes/systems_.$systemId.services'
import { Route as SystemsSystemIdMetricsRouteImport } from './routes/systems_.$systemId.metrics'
import { Route as SystemsSystemIdClusterRouteImport } from './routes/systems_.$systemId.cluster'
import { Route as SystemsSystemIdServicesUnitIdRouteImport } from './routes/systems_.$systemId.services_.$unitId'
import { Route as SystemsSystemIdPluginsPluginIdRouteImport } from './routes/systems_.$systemId.plugins.$pluginId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdRoute = SystemsSystemIdRouteImport.update({
  id: '/systems/$systemId',
  path: '/systems/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorSessionIdRoute = OperatorSessionIdRouteImport.update({
  id: '/operator_/$sessionId',
  path: '/operator/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdServicesRoute = SystemsSystemIdServicesRouteImport.update({
  id: '/systems_/$systemId/services',
  path: '/systems/$systemId/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdMetricsRoute = SystemsSystemIdMetricsRouteImport.update({
  id: '/systems_/$systemId/metrics',
  path: '/systems/$systemId/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdClusterRoute = SystemsSystemIdClusterRouteImport.update({
  id: '/systems_/$systemId/cluster',
  path: '/systems/$systemId/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdServicesUnitIdRoute =
  SystemsSystemIdServicesUnitIdRouteImport.update({
    id: '/systems_/$systemId/services_/$unitId',
    path: '/systems/$systemId/services/$unitId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemsSystemIdPluginsPluginIdRoute =
  SystemsSystemIdPluginsPluginIdRouteImport.update({
    id: '/systems_/$systemId/plugins/$pluginId',
    path: '/systems/$systemId/plugins/$pluginId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/operator': typeof OperatorRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/operator/$sessionId': typeof OperatorSessionIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems/$systemId/cluster': typeof SystemsSystemIdClusterRoute
  '/systems/$systemId/metrics': typeof SystemsSystemIdMetricsRoute
  '/systems/$systemId/services': typeof SystemsSystemIdServicesRoute
  '/systems/$systemId/plugins/$pluginId': typeof SystemsSystemIdPluginsPluginIdRoute
  '/systems/$systemId/services/$unitId': typeof SystemsSystemIdServicesUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/operator': typeof OperatorRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/operator/$sessionId': typeof OperatorSessionIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems/$systemId/cluster': typeof SystemsSystemIdClusterRoute
  '/systems/$systemId/metrics': typeof SystemsSystemIdMetricsRoute
  '/systems/$systemId/services': typeof SystemsSystemIdServicesRoute
  '/systems/$systemId/plugins/$pluginId': typeof SystemsSystemIdPluginsPluginIdRoute
  '/systems/$systemId/services/$unitId': typeof SystemsSystemIdServicesUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/operator': typeof OperatorRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/operator_/$sessionId': typeof OperatorSessionIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems_/$systemId/cluster': typeof SystemsSystemIdClusterRoute
  '/systems_/$systemId/metrics': typeof SystemsSystemIdMetricsRoute
  '/systems_/$systemId/services': typeof SystemsSystemIdServicesRoute
  '/systems_/$systemId/plugins/$pluginId': typeof SystemsSystemIdPluginsPluginIdRoute
  '/systems_/$systemId/services_/$unitId': typeof SystemsSystemIdServicesUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/operator'
    | '/settings'
    | '/terminal'
    | '/operator/$sessionId'
    | '/systems/$systemId'
    | '/systems/$systemId/cluster'
    | '/systems/$systemId/metrics'
    | '/systems/$systemId/services'
    | '/systems/$systemId/plugins/$pluginId'
    | '/systems/$systemId/services/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/operator'
    | '/settings'
    | '/terminal'
    | '/operator/$sessionId'
    | '/systems/$systemId'
    | '/systems/$systemId/cluster'
    | '/systems/$systemId/metrics'
    | '/systems/$systemId/services'
    | '/systems/$systemId/plugins/$pluginId'
    | '/systems/$systemId/services/$unitId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/operator'
    | '/settings'
    | '/terminal'
    | '/operator_/$sessionId'
    | '/systems/$systemId'
    | '/systems_/$systemId/cluster'
    | '/systems_/$systemId/metrics'
    | '/systems_/$systemId/services'
    | '/systems_/$systemId/plugins/$pluginId'
    | '/systems_/$systemId/services_/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  OperatorRoute: typeof OperatorRoute
  SettingsRoute: typeof SettingsRoute
  TerminalRoute: typeof TerminalRoute
  OperatorSessionIdRoute: typeof OperatorSessionIdRoute
  SystemsSystemIdRoute: typeof SystemsSystemIdRoute
  SystemsSystemIdClusterRoute: typeof SystemsSystemIdClusterRoute
  SystemsSystemIdMetricsRoute: typeof SystemsSystemIdMetricsRoute
  SystemsSystemIdServicesRoute: typeof SystemsSystemIdServicesRoute
  SystemsSystemIdPluginsPluginIdRoute: typeof SystemsSystemIdPluginsPluginIdRoute
  SystemsSystemIdServicesUnitIdRoute: typeof SystemsSystemIdServicesUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$systemId': {
      id: '/systems/$systemId'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof SystemsSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator_/$sessionId': {
      id: '/operator_/$sessionId'
      path: '/operator/$sessionId'
      fullPath: '/operator/$sessionId'
      preLoaderRoute: typeof OperatorSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$systemId/services': {
      id: '/systems_/$systemId/services'
      path: '/systems/$systemId/services'
      fullPath: '/systems/$systemId/services'
      preLoaderRoute: typeof SystemsSystemIdServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$systemId/metrics': {
      id: '/systems_/$systemId/metrics'
      path: '/systems/$systemId/metrics'
      fullPath: '/systems/$systemId/metrics'
      preLoaderRoute: typeof SystemsSystemIdMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$systemId/cluster': {
      id: '/systems_/$systemId/cluster'
      path: '/systems/$systemId/cluster'
      fullPath: '/systems/$systemId/cluster'
      preLoaderRoute: typeof SystemsSystemIdClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$systemId/services_/$unitId': {
      id: '/systems_/$systemId/services_/$unitId'
      path: '/systems/$systemId/services/$unitId'
      fullPath: '/systems/$systemId/services/$unitId'
      preLoaderRoute: typeof SystemsSystemIdServicesUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems_/$systemId/plugins/$pluginId': {
      id: '/systems_/$systemId/plugins/$pluginId'
      path: '/systems/$systemId/plugins/$pluginId'
      fullPath: '/systems/$systemId/plugins/$pluginId'
      preLoaderRoute: typeof SystemsSystemIdPluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  OperatorRoute: OperatorRoute,
  SettingsRoute: SettingsRoute,
  TerminalRoute: TerminalRoute,
  OperatorSessionIdRoute: OperatorSessionIdRoute,
  SystemsSystemIdRoute: SystemsSystemIdRoute,
  SystemsSystemIdClusterRoute: SystemsSystemIdClusterRoute,
  SystemsSystemIdMetricsRoute: SystemsSystemIdMetricsRoute,
  SystemsSystemIdServicesRoute: SystemsSystemIdServicesRoute,
  SystemsSystemIdPluginsPluginIdRoute: SystemsSystemIdPluginsPluginIdRoute,
  SystemsSystemIdServicesUnitIdRoute: SystemsSystemIdServicesUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
